CREATE TABLE IF NOT EXISTS ANOTACAO(
    ID_ANOTACAO INT AUTO_INCREMENT PRIMARY KEY, 
    TEXTO VARCHAR(8000)
);

CREATE TABLE IF NOT EXISTS AUTOR(
    ID_AUTOR INT AUTO_INCREMENT PRIMARY KEY, 
    NOME_AUTOR VARCHAR(255) NOT NULL, 
    COD_AUTOR VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TITULO(
    ID_TITULO INT AUTO_INCREMENT PRIMARY KEY, 
    NOME_TITULO VARCHAR(255) NOT NULL, 
    COD_TITULO VARCHAR(255) NOT NULL, 
    ID_AUTOR INT NOT NULL
);

ALTER TABLE TITULO ADD CONSTRAINT IF NOT EXISTS FK_TITULO_AUTOR FOREIGN KEY(ID_AUTOR) REFERENCES AUTOR(ID_AUTOR) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS EXEMPLAR(
    ID_EXEMPLAR INT AUTO_INCREMENT PRIMARY KEY,  
    COD_EXEMPLAR VARCHAR(255) NOT NULL, 
    ID_TITULO INT NOT NULL
);

ALTER TABLE EXEMPLAR ADD CONSTRAINT IF NOT EXISTS FK_EXEMPLAR_TITULO FOREIGN KEY(ID_TITULO) REFERENCES TITULO(ID_TITULO) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS USUARIO(
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY, 
    NOME_USUARIO VARCHAR(255) NOT NULL, 
    TEL_USUARIO VARCHAR(255), 
    EMAIL_USUARIO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS EMPRESTIMO(
    ID_EMPRESTIMO INT AUTO_INCREMENT PRIMARY KEY, 
    ID_USUARIO INT NOT NULL, 
    ID_EXEMPLAR INT NOT NULL, 
    DATA_EMPRESTIMO DATE NOT NULL, 
    DATA_DEVOLUCAO DATE NOT NULL
);

ALTER TABLE EMPRESTIMO ADD CONSTRAINT IF NOT EXISTS FK_EMPRESTIMO_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EMPRESTIMO ADD CONSTRAINT IF NOT EXISTS FK_EMPRESTIMO_EXEMPLAR FOREIGN KEY(ID_EXEMPLAR) REFERENCES EXEMPLAR(ID_EXEMPLAR) ON DELETE CASCADE ON UPDATE CASCADE;